version: pythonocc-core-0.16.5-dev.{build}

environment:
  oce_version: 0.16.1
  matrix:
    - generator: "MSYS Makefiles"
      Compiler: MinGW-gcc-4.8.1
      ARCH: "Win32"
    - generator: "MSYS Makefiles"
      ARCH: "i686"
      Compiler: MinGW-gcc-4.9.3
    - generator: "MSYS Makefiles"
      ARCH: "Win64"
      Compiler: MinGW64-gcc-5.2.0
    - generator: "Visual Studio 12"
      ARCH: "Win32"
      Compiler: "MSVC2013"
    - generator: "Visual Studio 12 Win64"
      ARCH: "Win64"
      Compiler: "MSVC2013"
    - generator: "Visual Studio 14"
      ARCH: "Win32"
      Compiler: "MSVC2015"
    - generator: "Visual Studio 14 Win64"
      ARCH: "Win64"
      Compiler: "MSVC2015"

cache:
  - i686-4.9.3-release-posix-dwarf-rt_v4-rev1.7z
  - x86_64-5.2.0-release-posix-seh-rt_v4-rev0.7z
  - OCE-0.16.1-Mingw32.zip

configuration:
  #- Debug
  - RelWithDebInfo

branches:
  only:
    - master
    - /^review/

shallow_clone: true 

init:

before_build:

install:

  ## Use Chocolatey to install SWIG.
  - choco install swig --version 3.0.6 -y

build_script:
  - cmd: if "%generator%" == "MSYS Makefiles" (C:\MinGW\msys\1.0\bin\sh --login /c/projects/pythonocc-core/ci/appveyor/make-pythonocc-core-msys.sh)
      else (CALL C:\projects\pythonocc-core\ci\appveyor\make-pythonocc-core-msvc.bat)

#after_build:
#  - cmd: 7z a oce-%oce_version%.%ARCH%.%Compiler%.zip C:\oce-%oce_version% > nul
#  - cmd: dir oce-%oce_version%.%ARCH%.%Compiler%.zip
#
#artifacts:
#  - path: oce-%oce_version%.%ARCH%.%Compiler%.zip

test: off  # to avoid discovering tests
